### ISSUE TITLE
Potential issue with intersections search/selection on map

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/311#933]
When searching for an intersection there are mixed results on whether it works or not.

It appears that there are certain intersections that exist more than once in the City and if they do appear more than once then there is an error and the user can't submit a case type.

When trying to submit Park and Beacon, there are three potential intersections a user could submit. When trying to submit the case, the following error appears:

![screen shot 2018-11-06 at 5 03 40 pm](https://user-images.githubusercontent.com/20731897/48096720-f5a82d00-e1e5-11e8-9abd-455ed9352352.png)

![screen shot 2018-11-06 at 4 50 46 pm](https://user-images.githubusercontent.com/20731897/48096739-0062c200-e1e6-11e8-8c68-c9cca434566f.png)

There is not an issue when only one result exists. Example: https://311-uat.digital-staging.boston.gov/reports/200983622

Reilly spoke with Claire briefly about this, so Claire knows we may be reaching out. We need more investigation on where the issue is occurring, but need developer help to do this.

**Comment by fionawhim** [comment]
This was a really good catch.

The bug was in our code.

Because there were multiple selections, some of the unit-handling code was being used, which caused us to try and create a case with the intersection as the address string.

The Salesforce implementation does not allow addresses to be specified as text, so we need to send them as lat/lng instead in every case.
